Repository 2019-swpp-8/swpp, pull requests merged in 2019-04, with the labels that each got.

#2 User profiles
  backend/README.md
  backend/backend/settings.py
  backend/backend/swpp/models.py
  backend/backend/swpp/views.py
  backend/backend/urls.py
  backend/swpp/__init__.py
  backend/swpp/admin.py
  backend/swpp/apps.py
  backend/swpp/migrations/0001_initial.py
  backend/swpp/migrations/0002_auto_20190416_1432.py
  backend/swpp/migrations/0003_profile_joined.py
  backend/swpp/migrations/0004_tutor.py
  backend/swpp/migrations/__init__.py
  backend/swpp/models.py
  backend/swpp/serializers.py
  backend/swpp/tests.py
  backend/swpp/urls.py
  backend/swpp/views.py
Labels: core feature

#5 Merge backend modularization to master
  backend/swpp/model/__init__.py
  backend/swpp/model/profile.py
  backend/swpp/model/tutor.py
  backend/swpp/model/user.py
  backend/swpp/models.py
  backend/swpp/serializer/__init__.py
  backend/swpp/serializer/profile.py
  backend/swpp/serializer/tutor.py
  backend/swpp/serializer/user.py
  backend/swpp/serializers.py
  backend/swpp/view/__init__.py
  backend/swpp/view/profile.py
  backend/swpp/view/tutor.py
  backend/swpp/view/user.py
  backend/swpp/views.py
Labels: fix

#7 Fix typo in views.py
  backend/swpp/views.py
Labels: fix

#12 Added diagrams for wiki
  wiki/Controller.png
  wiki/MVC.png
Labels: hw

#14 Add files via upload
  wiki/REST.png
Labels: hw progress

#15 Add design and planning document pdf
  wiki/Design and Planning Document.pdf
Labels: hw progress

#18 Implement backend coverage testing
  .travis.yml
  backend/swpp/tests.py
Labels: core feature

#19 README.md에 coverage 뱃지 추가
  README.md
Labels: enhancement
